ci: grant PR write permissions for actions-comment-pull-request action
We started seeing the error of the pr workflow [^1]:

    Run thollander/actions-comment-pull-request@v2
    No comment has been found with asked pattern. Creating a new comment.
    Error: Resource not accessible by integration

According to the thollander/actions-comment-pull-request action's
README[^2] we need to add pull-requestes: write permissions to the
workflow.

Do that and also update the action to v3 while at it.

[^1]: https://github.com/cilium/statedb/pull/151#issuecomment-4046941923
[^2]: https://github.com/thollander/actions-comment-pull-request/blob/e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa/README.md?plain=1#L172-L181

Signed-off-by: Tobias Klauser <tobias@cilium.io>