part: Add missing closing of root watch channel
The commit f8e6b9e416cc0 changed the implementation not to always have
a zero-prefix node4 at the root. This change unfortunately missed marking
the replaced root's watch channel for closing. This fixes the issue and
adds a validation to make sure any watch channel that no longer is referenced
in the new tree is closed.

=== RUN   Test_replaceRoot
node4[61]: 61 -> 1 (L:0x4000041b00 W:0x4000014a80 true) (N:0x400012c500, W:0x4000014bd0 false)
 leaf[62]: 6162 -> 3 (L:0x4000041b30 W:0x4000014b60 false) (N:0x4000041b30, W:0x4000014b60 false)
---
leaf[6162]: 6162 -> 3 (L:0x4000041bf0 W:0x4000014b60 false) (N:0x4000041bf0, W:0x4000014b60 false)
--- FAIL: Test_replaceRoot (0.00s)
panic: dropped watch channel 0x4000014bd0 at depth 0 not closed [recovered]
        panic: dropped watch channel 0x4000014bd0 at depth 0 not closed

Fixes: f8e6b9e416cc0 ("part: Remove the unnecessary empty root node")
Signed-off-by: Jussi Maki <jussi@isovalent.com>