part: Fix bug with short and long key with shared prefix
If we insert "foobar" and then "foo" we ended up in a case where
"foo" was the common prefix and the rest of the key become empty
leading to out-of-bounds access to the key slice.

Handle the case where the key becomes empty when splitting a node
by just inserting it as the leaf of the split node.

Added a regression test and validated it catched the bug:

--- FAIL: Test_prefix_regression (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 32 [running]:
testing.tRunner.func1.2({0x5f3380, 0xc00001a288})
        /home/jussi/sdk/go1.22.0/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
        /home/jussi/sdk/go1.22.0/src/testing/testing.go:1634 +0x377
panic({0x5f3380?, 0xc00001a288?})
        /home/jussi/sdk/go1.22.0/src/runtime/panic.go:770 +0x132
github.com/cilium/statedb/part.(*Txn[...]).insert(0x6725e0, ...
        /home/jussi/go/src/github.com/cilium/statedb/part/txn.go:228 +0xdaf

Signed-off-by: Jussi Maki <jussi@isovalent.com>